import {
  WEB_CLIENT_ID,
  IOS_CLIENT_ID,
  HASURA_GRAPHQL_ADMIN_SECRET,
  HASURA_GRAPHQL_ENDPOINT,
} from '@env';

export default {
  WEB_CLIENT_ID,
  IOS_CLIENT_ID,
  HASURA_GRAPHQL_ADMIN_SECRET,
  HASURA_GRAPHQL_ENDPOINT,
};
